title = u'beatmaniaIIDX INFINITAS リザルト手帳'
icon_path = 'icon.ico'
background_color = '#448d67'
background_color_label = '#af8c30'
selected_background_color = '#245d18'
in_area_background_color = '#5779dd'
